name = "firedre"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "firedre-blog"
database_id = "0a45a6b7-ab5e-4192-8c5b-92f055e06b97"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "firedre-blog"
